### ISSUE TITLE
Default partition is confusing

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-role-openhpc#149]
Because https://github.com/stackhpc/ansible-role-openhpc/blob/master/templates/slurm.conf.j2#L134 defaults to setting a partition to `Default=YES` if a group/partition in `openhpc_slurm_partitions` does not define the `default` parameter, in a case like this the second partition still ends up being the actual default in slurm:

```yaml
openhpc_slurm_partitions:
    - name: first
      default: YES
    - name: second
```

and `second` has to specifically be marked `default: NO` to make the first the default.
