### ISSUE TITLE
Molecule tests don't work in RL9.5

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-role-openhpc#177]
They need changing like this:

```yaml
#molecule/test*/molecule.yml
 platforms:
   - name: testohpc-login-0
+    hostname: testohpc-login-0
     image: ${MOLECULE_IMAGE}
     pre_build_image: true
     groups:
       - testohpc_login
     command: /sbin/init
     tmpfs:
-      - /run
-      - /tmp
+      /run: rw,size=128m
+      /tmp: rw,size=128m
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
     network: net1
```
.. and same for all other nodes in each file
