### ISSUE TITLE
Provide control over slurm.conf

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-role-openhpc#21]
At the moment the user has no way to change parameters in this. This meant the [enhanced-slurm](https://github.com/stackhpc/eiffel-ohpc/tree/vss) work had to fork the role.

Consider providing facilities to either override template values, and/or take a user-provided template.

**Comment by sjpb** [comment]
Could also consider allowing merge of user config files with something like https://github.com/openstack/kolla-ansible/blob/master/ansible/action_plugins/merge_configs.py.

Note that templating for nodenames/partitions is v dependent on the role logic so don't really want users to be able to mess with it.

**Comment by sjpb** [comment]
Current suggestion is to use the above merge config inside the role, something like:

```yaml
merge_configs:
  srcs: "{{ [ role_path + '/templates/slurm.conf.j2' ] + additional_slurm_conf }}"
  dest: /etc/slurm.conf
```

Need to consider how this is usable from the rebuild role.
