### ISSUE TITLE
Role should add/document requirement for OpenHPC repo

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-role-openhpc#24]
Currently this is normally done manually, e.g.:

```
  vars:
    openhpc_repo_url: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
  tasks:
    - name: Install OpenHPC repository
      yum:
        name: "{{ openhpc_repo_url }}"

```

Connnected to #6?
