### ISSUE TITLE
Ability to install given versions of OpenHPC

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-openhpc#6]
The role should (optionally?) install an RPM for the OpenHPC repo file for a named version.

For example, it would be good to supply an OpenHPC release version as parameter and have the effect of installing a repo like this:

```
    - name: Ensure the OpenHPC package repo rpm is present
      yum:
        name: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
        state: present

```

The deep link into the OpenHPC distribution package archives would be added (and maintained) by this role.  The user would name a version (eg, as `openhpc_version=v1.3`) and the role would maintain a dictionary of known versions and their repo URLs.
