### ISSUE TITLE
drain nodes example in README has un-supported parameters

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-role-openhpc#98]
Currently:
```
openhpc_slurm_partitions:
          - name: "compute"
            flavor: "compute-A"
            image: "CentOS7.5-OpenHPC"
            num_nodes: 6
            user: "centos"
```
`flavor`, `image`, `num_nodes`, `user` are not supported parameters. `num_nodes` occurs further down the example too.
